deploy

diff --git a/.github/workflows/staging_candidate_build.yml b/.github/workflows/staging_candidate_build.yml
--- a/.github/workflows/staging_candidate_build.yml
+++ b/.github/workflows/staging_candidate_build.yml
@@ -20,7 +20,8 @@ jobs:
             gh api ${{ github.event.issue.comments_url }} -f "body=@${{ github.event.issue.user.login }} Please make sure CI is greeen"
             exit 1
           fi
-          branches=`gh pr list -l staging | cut -d $'\t' -f 3 | sed "s/^/origin\//" | tr '\n' ' '`
+          branches_list=`gh pr list -l staging | cut -d $'\t' -f 3`
+          branches=`echo "$branches_list" | sed "s/^/origin\//" | tr '\n' ' '`
           candidate_branches=`gh pr list -l 'staging candidate' | cut -d $'\t' -f 3 | sed "s/^/origin\//" | tr '\n' ' '`
           git fetch
           git config --global user.email "staging@indeedflex.com"
@@ -32,11 +33,65 @@ jobs:
           set -e
           if [ $merge_staging_branches -ne 0 ];
           then
-            printf "{\"body\": \"@${{ github.event.issue.user.login }} unable to merge 'Staging' PRs\\\n\`\`\`\\\ngit checkout master\\\ngit merge master $branches # <-- error, Staging\\\n\`\`\`\"}" | gh api ${{ github.event.issue.comments_url }} --input -
+            error_message=""
+            master_unmergable_branches=()
+            master_mergable_branches=()
+            for branch in $branches_list
+            do
+              set +e
+              git reset -q --hard origin/master
+              git merge -q --no-edit origin/$branch 2>/dev/null
+              merge_result=$?
+              set -e
+              if [ $merge_result -ne 0 ];
+              then
+                master_unmergable_branches+=($branch)
+              else
+                master_mergable_branches+=($branch)
+              fi
+            done
+            for branch in $master_unmergable_branches
+            do
+              details=`gh api "/repos/2rba/github_test/pulls?state=open&head=2rba:$branch" -q '[.[0].number, .[0].user.login]|@tsv'`
+               while IFS=$'\t' read -r number login
+               do
+                 printf -v error_message "$error_message\nPR #$number cannot be merged to master, please rebase/merge or unlabel the PR. cc @$login"
+               done < <(echo "$details")
+            done
+
+            for ((i1 = 0; i1 <= ${#master_mergable_branches[@]}; ++i1))
+            do
+            for ((i2 = i1+1; i2 < ${#master_mergable_branches[@]}; ++i2))
+            do
+              branch1=${master_mergable_branches[$i1]}
+              branch2=${master_mergable_branches[$i2]}
+              set +e
+              git reset -q --hard origin/master
+              git merge -q --no-edit origin/$branch1 origin/$branch2  2>/dev/null
+              merge_result=$?
+              set -e
+              if [ $merge_result -ne 0 ];
+              then
+                details1=`gh api "/repos/2rba/github_test/pulls?state=open&head=2rba:$branch1" -q '.[]|select(.labels[].name == "Staging") | [.number, .user.login]|@tsv'`
+                details2=`gh api "/repos/2rba/github_test/pulls?state=open&head=2rba:$branch2" -q '.[]|select(.labels[].name == "Staging") | [.number, .user.login]|@tsv'`
+                while IFS=$'\t' read -r number1 login1
+                do
+                while IFS=$'\t' read -r number2 login2
+                do
+                  login=`printf "$login1\n$login2" | uniq`
+                  error_message="$error_message \nPR #$number1 and PR #$number2 have conflicts, please resolve or unlabel. cc @$login"
+                done < <(echo "$details2")
+                done < <(echo "$details1")
+              fi
+            done
+            done
+
+            printf "{\"body\": \"@${{ github.event.issue.user.login }} unable to merge 'Staging' PRs\\\n\`\`\`\\\ngit checkout master\\\ngit merge master $branches # <-- error, Staging\\\n\`\`\`\\\\n$error_message"}" | gh api ${{ github.event.issue.comments_url }} --input -
             gh api -X DELETE ${{ github.event.comment.issue_url }}/labels/staging\ candidate || true
             gh api -X DELETE ${{ github.event.comment.issue_url }}/labels/Staging || true
             exit 1
           fi
+
           set +e
           git merge --no-edit master $candidate_branches
           merge_staging_candidate_branches=$?
